### ISSUE TITLE
There might be mistakes in the perimeter network diagram

### ISSUE THREAD

**Issue by sdzhangtao** [aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium#12]
There might be mistakes in the routing tables associated with Perimeter PerimeterNat and Perimeter-Tgw route tables.
The diagram is located here.
https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium/blob/main/architecture-doc/images/network/high-level-network-Perimeter.drawio.png

The network firewall is located at perimeter subnet. And the design principal is to direct all traffic to network firewall first.  
So:
For Perimeter route table, 
  0.0.0.0/0 -> nat gateway
  Supernet -> Tgw
  
For PerimeterNat route table, this subnet  contains the NAT gateway
  0.0.0.0/0 -> igw
  Supernet -> Network firewall
  
 For Perimeter-Tgw route table
   0.0.0.0/0 -> network firewall
   
The PerimeterNat should be our public subnet.

**Comment by rjjaegeraws** [comment]
Hi sdzhangtao,

Thanks for creating this issue. I will review this with the team.

**Comment by rjjaegeraws** [comment]
Hi sdzhangtao,

The current diagram aligns with the changes introduced in version [1.9.2-b](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium/blob/main/CHANGELOG.md#192-b-2024-09-10) with the addition of the `IGW-Ingress-Routes` route table.

The routes described above are those in place prior to this change. Detailed instructions to make the changes can be found [here](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium/blob/main/documentation/1-9-2b-nfw-update-instructions.md)

**Comment by sdzhangtao** [comment]
Hi Ryan,

Thanks for your reply. I see it now and I like it a lot better with this change. 
Our current version is 1.10.x. So I think it's better to apply the 1.9.2-b changes.
