### ISSUE TITLE
Workload account egress internet traffic flow squence diagram issue

### ISSUE THREAD

**Issue by sdzhangtao** [aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium#15]
There might be a mistake in the egress internet traffic from workload VPC.

The outbound internet traffic arrives at the Perimeter-Tgw subnet and follow the subnet route table, the traffic will be directed to the Perimeter subnet which hosts the firewall. After firewall inspects traffic, and will use Perimeter subnet route table, which will direct traffic to Perimeter-Nat subnet, which finally will forward traffic to internet gateway. 

From the diagram, the traffic flows from Transit Gateway attachment to Nat and then to firewall.   

https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium/blob/main/architecture-doc/images/network/high-level-network-Member%20Account%20Egress.drawio.png

**Comment by rjjaegeraws** [comment]
Hi sdzhangtao,

Please review the latest networking changes, per the comment added to your first opened issue [here](https://github.com/aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium/issues/12).

**Comment by sdzhangtao** [comment]
Thanks, it matches with 1.9.2-b perfectly
