### ISSUE TITLE
(Enhancement) AWS Config Aggregator needs to be configured

### ISSUE THREAD

**Issue by bernardosw-aws** [aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium#3]
AWS Config Aggregator functionality is not enabled and, therefore, AWS Config configuration and compliance data needs to be done at the account-level.

By enabling the Aggregator and configuring it to leverage the `Audit` account, authorized administrators/users can centrally review configuration and compliance data from all AWS Accounts in the AWS Organization from the Audit account.

**Comment by oliviergaumond** [comment]
This has been handled in v1.6.0-a
