### ISSUE TITLE
CloudFormation - Number of resources limit reached on the Central Network Account for NetworkVpcStack

### ISSUE THREAD

**Issue by JimToupet** [aws-samples/landing-zone-accelerator-on-aws-for-cccs-medium#9]
We tried to add a VPC into the Central Network account (with all subnets, nacl, ipam pool, etc) that leads to an error from number of resources in the CloudFormation Stack. 

2024-07-23 20:50:35.613 | error | accelerator | Number of resources in stack 'AWSAccelerator-NetworkVpcStack-XXXXXXXXX-ca-central-1': 546 is greater than allowed maximum of 500:

We read that this is a "hard" limit that can't be bypass. 

What are the possibilities ? We saw that nested stack is a way to prevent this but how while it's the LZA that generate those stacks?

LZA version : 1.62

**Comment by rjjaegeraws** [comment]
Hi JimToupet

This issue should be logged with the LZA [repo](https://github.com/awslabs/landing-zone-accelerator-on-aws), and ideally with AWS Support (AWS Console -> Support -> Control Tower -> Landing Zone Accelerator). However, I will also raise awareness with the team internally.

**Comment by rjjaegeraws** [comment]
This may be the same issue: https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/320
